### PR TITLE
Added writeups for Break In CTF - 2017

### PR DESCRIPTION
**Pull request by ironmaniiith**
Added write-ups for Break In CTF'17.

Ironmaniiith: [aalekh.jain@research.iiit.ac.in](mailto:aalekh.jain@research.iiit.ac.in)

### CODE REVIEW

**Comment by dhanvi** [comment]
The tasks looks good to me, 

I was waiting to merge the PR just to see if the file name in windows can have `!` 

It would have been better if the folder name ended with the challenge points. 

It would be better if you link the direct URL of the writeup instead of the ctftime.org URL

**Comment by ironmaniiith** [comment]
We had equal scores for all the problems (100)

Will update the URL.

**Comment by dhanvi** [comment]
Well it's not compulsory to end the folder name with points, since all the challenges have same points it is not at all required. 

Once you change the urls I will merge this PR

**Comment by m1ghtym0** [comment]
OMG, i blew it again, so sorry! I should check PR's more frequently before doing stuff!
Just fix the things @dhanvi said and will will merge it and integrate my stuff into yours!
Thanks for you work!

**Comment by ironmaniiith** [comment]
@m1ghtym0 
I have added the direct links. Also there are several issues with the work added by you, so it would be great if you directly merge this work.

**Comment by dhanvi** [comment]
@ironmaniiith 
I don't find anything wrong with what @m1ghtym0 added here, would you mind explaining the issues that you mentioned in the above comment?
`Also there are several issues with the work added by you`

We can merge this PR and mix both the stuff. 

@ironmaniiith deleting the existing folder is a bad idea IMHO as work done by @m1ghtym0 will be lost! 
We will try to make sure that people won't do redundant stuff. 

@m1ghtym0 Take a note to always check PR's! :smile:

**Comment by ironmaniiith** [comment]
1. No requirement of scores to be appended at the last
2. No entries in "External write-ups" only
3. No missing writeups.
4. Scoreboard link is different, it will be invalid in few days (as we will close the contest portal in few days). Also local scoreboard needs to be added.
5. The contest link given at the top of the readme is the one where we made the contest live, it's not the official contest page link.
6. I see the many statements like `The flag is: the_flag_is_6bdfde3455a864cde19362cc01da125f` which is not valid, as the flag in the above case is just `The flag is: 6bdfde3455a864cde19362cc01da125f` (Instructions were already given regarding the flag format before the contest)

**Comment by m1ghtym0** [comment]
Thanks for your work @ironmaniiith! I don't see anything that's left to merge in my work, so
I will check once again and then remove it. @dhanvi thanks for you appreciation, but I there isn't anything in my folder that @ironmaniiith hasn't covered. I should better check PR's beforehand next time:D

**Comment by ironmaniiith** [comment]
:+1:

**Pull request merged**
